// This file is part of Butane. See README.md and LICENSE.md for details.
// Copyright (c) 2012 Michael Williams <devbug@bitbyte.ca>

#ifndef _BUTANE_PIXEL_FORMAT_H_
#define _BUTANE_PIXEL_FORMAT_H_

#include <bt/foundation.h>
#include <bt/config.h>

#define BT_PIXEL_FORMAT_COLOR_BIT      (1u << 31u)
#define BT_PIXEL_FORMAT_DEPTH_BIT      (1u << 30u)
#define BT_PIXEL_FORMAT_STENCIL_BIT    (1u << 29u)
#define BT_PIXEL_FORMAT_COMPRESSED_BIT (1u << 28u)

#define BT_PIXEL_FORMAT_FLAGS_MASK 0xF0000000u
#define BT_PIXEL_FORMAT_TYPE_MASK  0x0FFFFFFFu

namespace bt {
  enum PixelFormat {
    BT_PIXEL_FORMAT_R8G8B8A8 =
      0x00000001u | BT_PIXEL_FORMAT_COLOR_BIT,

    BT_PIXEL_FORMAT_R8G8B8A8_SRGB =
      0x00000002u | BT_PIXEL_FORMAT_COLOR_BIT,

    BT_PIXEL_FORMAT_DXT1 =
      0x00000003u | BT_PIXEL_FORMAT_COLOR_BIT | BT_PIXEL_FORMAT_COMPRESSED_BIT,

    BT_PIXEL_FORMAT_DXT3 =
      0x00000004u | BT_PIXEL_FORMAT_COLOR_BIT | BT_PIXEL_FORMAT_COMPRESSED_BIT,

    BT_PIXEL_FORMAT_DXT5 =
      0x00000005u | BT_PIXEL_FORMAT_COLOR_BIT | BT_PIXEL_FORMAT_COMPRESSED_BIT,

    BT_PIXEL_FORMAT_D24_S8 =
      0x00000006u | BT_PIXEL_FORMAT_DEPTH_BIT,
  };
} // bt

#endif // _BUTANE_PIXEL_FORMAT_H_