#===-- Makefile ---------------------------------------------*- Makefile -*-===#
#
#  Butane, a data-driven game engine.
#
#  This file is distributed under the terms described in LICENSE.
#
#  Author(s):
#
#    * Michael Williams <mwilliams@bitbyte.ca>
#
#===------------------------------------------------------------------------===#
include src/bitbyte/butane.mk

#===------------------------------------------------------------------------===#
